DROP DATABASE IF EXISTS FITNESS;

CREATE DATABASE FITNESS;

USE FITNESS;

DROP TABLE IF EXISTS `LOCKER`;

CREATE TABLE `LOCKER` (
	`LOCKER_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`LOCATION`	VARCHAR(10)	NOT NULL
);

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`MEMBER_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	VARCHAR(20)	NOT NULL,
	`CONTACT`	VARCHAR(13)	NOT NULL,
	`JOIN_DATE`	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`LOCKER_ID`	INT	UNIQUE NULL
);

DROP TABLE IF EXISTS `CLASS`;

CREATE TABLE `CLASS` (
	`CLASS_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	VARCHAR(20)	NOT NULL,
	`CAPACITY`	INT	NOT NULL,
	`FEE`	INT	NOT NULL,
	`TRAINER_ID`	INT	NOT NULL
);

DROP TABLE IF EXISTS `TRAINER`;

CREATE TABLE `TRAINER` (
	`TRAINER_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`NAME`	VARCHAR(20)	NOT NULL,
	`SPECIALTY`	VARCHAR(20)	NULL,
	`EXPERIENCE`	INT	NOT NULL DEFAULT 0,
	`MANAGER_ID`	INT	NULL
);

DROP TABLE IF EXISTS `ENROLLMENT`;

CREATE TABLE `ENROLLMENT` (
	`ENROLLMENT_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`APPLY_DATE`	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`PAYMENT_STATE`	VARCHAR(3)	NOT NULL,
	`MEMBER_ID`	INT	NOT NULL,
	`CLASS_ID`	INT	NOT NULL
);

DROP TABLE IF EXISTS `ATTENDANCE`;

CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_ID`	INT	PRIMARY KEY AUTO_INCREMENT,
	`CHECK_IN_TIME`	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MEMBER_ID`	INT	NOT NULL,
	`CLASS_ID`	INT	NOT NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_LOCKER_TO_MEMBER_1` FOREIGN KEY (
	`LOCKER_ID`
)
REFERENCES `LOCKER` (
	`LOCKER_ID`
);

ALTER TABLE `CLASS` ADD CONSTRAINT `FK_TRAINER_TO_CLASS_1` FOREIGN KEY (
	`TRAINER_ID`
)
REFERENCES `TRAINER` (
	`TRAINER_ID`
);

ALTER TABLE `TRAINER` ADD CONSTRAINT `FK_TRAINER_TO_TRAINER_1` FOREIGN KEY (
	`MANAGER_ID`
)
REFERENCES `TRAINER` (
	`TRAINER_ID`
);

ALTER TABLE `ENROLLMENT` ADD CONSTRAINT `FK_MEMBER_TO_ENROLLMENT_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `ENROLLMENT` ADD CONSTRAINT `FK_CLASS_TO_ENROLLMENT_1` FOREIGN KEY (
	`CLASS_ID`
)
REFERENCES `CLASS` (
	`CLASS_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_MEMBER_TO_ATTENDANCE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_CLASS_TO_ATTENDANCE_1` FOREIGN KEY (
	`CLASS_ID`
)
REFERENCES `CLASS` (
	`CLASS_ID`
);

